services:
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379

  todo_app:
    build:
      context: .
      target: builder
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis